[package]
name = "abridge"
version = "1.0.0"
edition = "2018"
author = "passthroo"

[dependencies]
clap = {version = "^2.33.3", features = ["yaml"]}
more-asserts = "^0.2.1"
substring = "^1.4.0"

[lib]

[[bin]]
name = "abridge"
