[package]
name = "abridge"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = {version = "^2.33.3", features = ["yaml"]}
more-asserts = "^0.2.1"
substring = "^1.4.0"

[lib]

[[bin]]
name = "abridge"
